apiVersion: v1
kind: Service
metadata:
  name: microservice-favorite-consumer
spec:
  type: NodePort
  ports:
  - port: 6801
    targetPort: 6801   # 节点暴露给外部的端口（范围必须为30000-32767）
    nodePort: 30006
  selector:
    app: microservice-favorite-consumer
