apiVersion: v1
kind: Service
metadata:
  name: microservice-favorite
spec:
  type: NodePort
  ports:
  - port: 680
    targetPort: 6800   # 节点暴露给外部的端口（范围必须为30000-32767）
    nodePort: 30004
  selector:
    app: microservice-favorite
