apiVersion: v1
kind: Service
metadata:
  name: microservice-discovery-eureka
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    # 节点暴露给外部的端口（范围必须为30000-32767）
    nodePort: 30000
  selector:
    app: microservice-discovery-eureka
