apiVersion: v1
kind: ReplicationController
metadata:
  name: microservice-bookmark
spec:
  # 节点数，设置为多个可以实现负载均衡效果
  replicas: 1
  selector:
    app: microservice-bookmark
  template:
    metadata:
      labels:
        app: microservice-bookmark
    spec:
      containers:
      - image: microservice-bookmark
        imagePullPolicy: IfNotPresent
        name: microservice-bookmark