apiVersion: v1
kind: Service
metadata:
  name: microservice-bookmark
spec:
  type: NodePort
  ports:
  - port: 6900
    targetPort: 6900
    # 节点暴露给外部的端口（范围必须为30000-32767）
    nodePort: 30001
  selector:
    app: microservice-bookmark
