apiVersion: v1
kind: Service
metadata:
  name: microservice-bookmark-consumer
spec:
  type: NodePort
  ports:
  - port: 6901
    targetPort: 6901
    # 节点暴露给外部的端口（范围必须为30000-32767）
    nodePort: 30002
  selector:
    app: microservice-bookmark-consumer
