spring:
  security: #开启安全验证
    user:
      name: hoob #用户名
      password: hoobzhu #密码
server:
  port: 8761
eureka:
  instance:
    hostname: microservice-eureka  #设置eureka实例名，与配置文件的变量为主
  client:
    register-with-eureka: false #由于当前这个应用就是Eureka Server，故而设为false 
    fetch-registry: false #
    service-url:
      defaultZone: http://hoob:hoobzhu@localhost:8761/eureka
      #http://${spring.security.user.name}:${spring.security.user.password}@eureka1:${server.port}/eureka/  eureka注册中心地址
#  enable-self-preservation: false #关闭自我保护：true开启 false关闭 默认true
  server: 
    eviction-interval-timer-in-ms: 5000 #清理间隔（单位毫秒， 默认是60*1000）
    enable-self-preservation: true #默认为true，设置为false，关闭自我保护
    #eureka server： 在运行期间会去统计心跳失败比例在15分钟之内是否低于85%
    renewal-percent-threshold: 0.49 #默认0.85
