apiVersion: v1
kind: Service
metadata:
  name: microservice-config-server
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    # 节点暴露给外部的端口（范围必须为30000-32767）
    nodePort: 30003
  selector:
    app: microservice-config-server
