apiVersion: v1
kind: Service
metadata:
  name: microservice-zuul
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000   # 节点暴露给外部的端口（范围必须为30000-32767）
    nodePort: 30010
  selector:
    app: microservice-zuul
